### ISSUE TITLE
error creating SSM parameter (/mwaa/ENV): ParameterAlreadyExists

### ISSUE THREAD

**Issue by mikmorley** [DNXLabs/terraform-aws-mwaa#6]
### Contact Details (optional)

michael.morley@plutora.com

### Description. What happened?

When using this module to deploy **another** MWAA instance to `us-west-2`, receive the following error:

```
│ Error: error creating SSM parameter (/mwaa/ENV): ParameterAlreadyExists: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.
│ 
│   with module.airflow["prod-us-airflow"].aws_ssm_parameter.mwaa_env,
│   on .terraform/modules/airflow/ssm.tf line 1, in resource "aws_ssm_parameter" "mwaa_env":
│    1: resource "aws_ssm_parameter" "mwaa_env" {
```

I'm not sure why the `/mwaa/ENV` parameter is required, but can you please update this to make this optional if it is not required, or it should be specific to environment, e.g. `/mwaa/${var.environment}/ENV`

### Steps to reproduce

1. Plan
2. Apply (Error on apply)

### Actual behavior

1. Plan
2. Apply
3. Success

### Occurrence

Frequently

### Relevant log output

```shell
│ Error: error creating SSM parameter (/mwaa/ENV): ParameterAlreadyExists: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.
│ 
│   with module.airflow["prod-us-airflow"].aws_ssm_parameter.mwaa_env,
│   on .terraform/modules/airflow/ssm.tf line 1, in resource "aws_ssm_parameter" "mwaa_env":
│    1: resource "aws_ssm_parameter" "mwaa_env" {
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FabioORamos** [comment]
We are disabling the creation of SSM parameters. This variable is not required and was only used during the update environment. This issue would only arise if you are deploying two MWAA in the same account and region.
